### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Sal-gamer** [PatnosDD/Hollow-Knight-PsVita#12]
Are you still going to continue updating this game for the PS Vita?

**Comment by ItsSamStone** [comment]
Random, but just wanted to add to this as well, if you wouldn't mind! First and foremost, Hollow Knight for PS Vita is nearly perfect... I can deal with the little remaining bugs in it's most current state, which are pretty much next to none IMO, except for a few remaining issues (the first of the two being the most important) as follows: 

1.) There are random stutters that can occur during boss fights and sometimes while exploring (especially annoying when trying to hop to different platforms and falling instead LOL). These stutters can be pretty large and negatively impactful at times... enough to interrupt you and cause your defeat if not playing predictively because of this. I've messed around with overclock settings and the video settings within the game, but the random stutters can still occur no matter how high I OC and how low I set the video settings and resolution. 

2.) Load times are reportedly much better than they were prior to the most current version. However, they are still a tad long IMO, at about ~15-30 seconds... but it's not a big deal IMO either because I can deal with it and am not very impatient in general. If they could be somehow optimized to be maybe 10 seconds, that would be awesome... but I'm not expecting any improvements here because, I mean, you're working with the freaking PS Vita! Haha. 

In conclusion, the largest remaining issue I would say would be issue #1, as seen above. If the random stutters could be fixed, the game would be 100% perfect, IMHO. However, I'm happy the way it is and can deal with it if they can't be mitigated with another update. Who am I to complain anyways! I'm not a programmer... creatively, I'm a musician and am just glad to have the ability to comfortably (since the PS Vita is the most comfy handheld console ever) play freaking Hollow Knight on-the-go via my beautiful OLED PS Vita... but hey, I figured I'd put my 2 cents in since another person (OP) was curious about the update status of this port! 

PS. Patnos - just like I've said to Rinne over and over again via many different social forums, etc... incredible job altogether, my friend. You are one of the greats in terms of the PS Vita's legacy and history. It may sound silly, but you will go down in history for helping save this amazing little console, and with how impressive your work has been, I'm sure these will be successes that can be included on your resume and help you book incredibly jobs in the gaming world in your future. I hope to see you and the other PS Vita Creatives continue making amazing creations and ports for the PS Vita, and I wish you all the most success in the world AND in all your endeavors. You've really become a huge part in bringing the console back to life AND keeping it alive. The PS Vita certainly deserves it after the way it was treated by Sony. We love you, brotha!
